---
title: Sustituir los límites de palabras con patrones de expresiones regulares en Python
hero_image: images/banner.png
description: Usar límites de palabras en sustituciones regex
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "regex, python"
site_areas:
steps:
  - 
    title: Límites de palabras

