---
title: Substitute word boundaries with regex patterns in Python
hero_image: images/banner.png
description: Use word boundaries in regex substitutions
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "regex, python"
site_areas:
steps:
  - 
    title: Word boundaries

